### ISSUE TITLE
Explain server reference in build.gradle [@Daron] 

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#209]
I found a reference to https://itemis.blackstardlb.nl
1. What is the role of this server?
2. How does this server work?
3. Will the MPS Flint IDE break if this is no longer accessible?

Found in [build.gradle](https://github.com/discipl/flinteditor-mps/blob/master/build.gradle)

**Comment by blackstardlb** [comment]
In the ci we use https://itemis.blackstardlb.nl because the github ci machines had issues accessing https://projects.itemis.de/nexus/content/repositories/mbeddr. https://itemis.blackstardlb.nl is a nginx proxy to https://projects.itemis.de/nexus/content/repositories/mbeddr. 
```
    server {
        listen              443 ssl;
        listen              [::]:443 ssl;
        server_name         itemis.blackstardlb.nl;
        ssl_certificate     /certs/blackstardlb.nl.crt;
        ssl_certificate_key /certs/blackstardlb.nl.key;
        location ^~ / {
            proxy_pass              https://projects.itemis.de/nexus/content/repositories/mbeddr/;
        }
    }
```
This is only used when running gradle commands in the CI (while running automated tests / making a release) so would not break the IDE if its no longer available.
