### ISSUE TITLE
Validate module overview

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#221]
Based on the sequence diagrams and `https://dslfoundry.com/mps-technology-stack-project-concepts-and-openapi-relations-explained-visually/`, I created a abstract module overview of the Flint IDE. Did I miss any modules in the software?

![image](https://user-images.githubusercontent.com/16115406/183431092-db24dfbf-aada-4606-b697-000369e42398.png)

![image](https://user-images.githubusercontent.com/16115406/183426655-6a91ca74-c1d4-42b0-b19a-b1092b7f3443.png)

**Comment by TristanAlbers** [comment]
@cblazo 

## Feedback Model 1
### DSLFoundry
Though im not familiar with this specific model and have some questions about it we should use it an quote [The DSLFoundry](https://dslfoundry.com/mps-technology-stack-project-concepts-and-openapi-relations-explained-visually/) as an authority on this matter. Some parts i don't quite follow on the DSLFoundry's part
is the SModel, OPENAPI and Generated Code part. An SModel is an MPS model defined in "Java code". This is part of the OPENAPI library. Furthermore OPENAPI (and thus SModel)
may seem like Java code but are actually DSL themselves. They need to be converted to Java code (I figure this happens when you build the project) before they can be used. Besides this the 'Generated Code' part having only a link to structure is a bit misleading since everything inside MPS (Behaviour, Structure, Constraints) is converted to plain Java for use. These are my observations, im interested to know more about this because it might be a matter of interpretation of the model.

### Flint specific
The transformers, services and clients are different from behaviours like `LawSource_Behaviour` and `Act_Behaviour` but are still placed inside the 'behaviour' folder since it adds functionality to the Language behaviour. I would suggest placing them inside the 'behaviour' block.

Futhermore i don't think we have clearly defined clients inside the Flint Language on the MPS side. At least i am not able to find any files named 'Client'.

Lastly i don't see anything that mentions the more low level languages used to assist Flint. We ofcourse have the `Flint Language` for interpretations but also the `LawSource Language` for source and the `Flint.plugin` model for extra editor functionalities. I don't know if this is intended or not.

## Feedback Model 2
### PublicationParserSelector
This directly interfaces with `ParserService` to gather the parsers.

### Editor
I believe this can be removed. The only block without a link would be `ParserService` which should be linked to `PublicationParserSelector` as stated above.

### FileChooser
`FileChooser` is linked to `DocumentStructureService` instead of `VersionBehaviour`. (`FileChooser` is a part of `VersionBehaviour` so the current link is also technically correct)

### BaseNsxTextlineClient
`NsxTransformingClient` has a reference to `BaseNsxTextlineClient` and makes calls to it but does not extend it. Maybe position `BaseNsxTextlineClient` a bit more to the right to show this distinction.

**Comment by cblazo** [comment]
Thanks. Regarding model 2, I made the changes you suggested. For model 1 I am not sure how it should look. I think we can indeed leave the leftmost elements out, and just zoom in on the Flint plugin. Could you help me make improved diagrams that helps us look ~2 levels into the black box of the Flint plugin?

I got this far:
1) Flint plugin contents: However, it's unclear to me what each language and solution means (besides Flint and LawSource)
![image](https://user-images.githubusercontent.com/16115406/183602846-6682dc17-6a59-4b1a-b4f7-683c4b049dc9.png)

2) Language components: The colors do not mean anything but help readers connect them with the ones in the view of (3)
![image](https://user-images.githubusercontent.com/16115406/183602804-17db7aa8-3baa-4e2e-8b98-c6e8dbdc7db9.png)

3) A zoomed in view of the Editor file of LawSource. What components do the editors and behaviours of the other Languages (especially Flint) look like?
![image](https://user-images.githubusercontent.com/16115406/183603407-93e724ab-878b-424b-a40d-8ce7e0d239bf.png)

**Comment by TristanAlbers** [comment]
1. It looks complete, i'll look a bit more into the dependencies of each language/solution so you can also see which language/solution uses the other ones. I'll draft an example diagram of what i mean. Im also curious what the specific use of this model should be. I assume an complete overview of all the languages/solutions in the Plugin right?

2. This is correct, you could even change the "Service, Clients, Transformers" into a single block named "Custom Behaviour Code" and it would be applicable to every MPS language

3. I'll draw up an example model of Act_Editor in the same style and come back to you to check.

**Comment by cblazo** [comment]
1. The goal is to show and explain the 'modules' of which the complete Flint plugin consists. If it is relatively easy to add dependencies/connections, that would be nice, but it is less important.

A relevant question for the report is: What is the role of each module?

**Comment by TristanAlbers** [comment]
Regarding point diagram 1, Something like this? Contains all languages and solutions with their respective links to eachother.

![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/37440544/183654374-8277c515-bc43-4ae2-9373-96b9d2d98822.png)

**Comment by TristanAlbers** [comment]
@cblazo 
Regarding point 3 i opted to first make a sequence diagram to more clearly see which classes/functions are called by the editor resulting in the diagram below. Is this something i should continue with or are the individual classes with connecting lines enough?  Also, this  diagram only shows what happens when the editor is openend. Depending on what actions a user takes in the editor a multitude of flows can be executed. I'll leave the decision up to you for futher steps.

- Should i continue making sequence diagrams or just component diagrams
- When continuing with sequence diagrams do you want all possible flows documented.

![image](https://user-images.githubusercontent.com/37440544/183679266-a49743ba-2652-4851-9c41-49a0e9b92f0e.png)

**Comment by cblazo** [comment]
1. This looks amazing and can go directly into our report, could you provide some descriptions of each element?
3. The sequence diagrams and component diagrams are a great resource for communicating with technical stakeholders. So this would be great for documentation, but has less priority than (1).

**Comment by TristanAlbers** [comment]
## Descriptions

### Solutions
- plugin
    - Used to define functionalities which use the "Project" context such as publication parser, FlintFiller, FlintRunner.   
    Also contains functionalities to bridge between Flint and LawSource such as NodeFromArticle intentions.
- runtime
    - Used to store runtime dependencies.
- test
    - Used to run developer tests on the Flint Plugin.
- FlintView
    - Used to create the custom FlintView.
- mainBuild
    - Build solution per MPS convention containing links to all build scripts.
- build
    - Build solution per MPS convention containing the individual build script for the Languages, Flint Plugin and Flint IDE.


### Languages
- Flint
    - Language containing all the functionalities for creating/editing Flint interpretations.
- LawSource
    - Language containing all the functionalities for creating/editing NormSources.
- FlintTest
    - Language used to mock certain functions of `Flint` and `LawSource`. Finds it usage in the `test` solution.
- FlintCellModels
    - Helper language to more easily define translated editor properties and tag cells. Finds it usage in the editors of the `Flint` Language.
- Resources
    - Helper language used to create/access/store resource files used in the `runtime` solution
- ParameterizedRangeSelection
    - Helper language used to create a custom intention. This intention can have parameters and can span over a range of nodes.  
    Based on `de.itemis.mps.selection.intentions`
